---
- name: "Replace line containing {{ line_to_change }} on file {{ filename }}"
  lineinfile:
    path: "{{ filename }}"
    regexp: "{{ line_to_change }}"
    line: "{{ change }}"
    when: not replace_mode

- name: "Replace string {{ line_to_change }} on file {{ filename }}"
  replace:
    path: "{{ filename }}"
    regexp: "{{ line_to_change }}"
    reaplce: "{{ change }}"
  when: replace_mode
